#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

decomposePar -force
#icoFoam > run.log 2>&1
mpirun -np 24 icoFoam -parallel > run.log 2>&1
sh post.sh
postProcess -func sample
foamToVTK
#------------------------------------------------------------------------------
